In [53]:
import torch
torch.__version__

'2.6.0+cu124'

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [55]:
# scalar
# creating pythorch tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [56]:
scalar.ndim

0

In [57]:
scalar.item()

7

In [58]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [59]:
vector.shape

torch.Size([2])

In [60]:
#Matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [61]:
MATRIX.ndim

2

In [62]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [63]:
TENSOR.shape

torch.Size([1, 3, 3])

In [64]:
#Random Tensors

In [65]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7698, 0.6748, 0.8255, 0.9220],
        [0.6923, 0.7422, 0.7206, 0.3030],
        [0.5679, 0.5076, 0.0078, 0.8804]])

In [66]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [67]:
torch.rand(3,3)

tensor([[0.6205, 0.6852, 0.9223],
        [0.8263, 0.5729, 0.8855],
        [0.0080, 0.0665, 0.5440]])

In [68]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [70]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [71]:
ones.dtype

torch.float32

In [72]:
random_tensor.dtype

torch.float32

In [73]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [77]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [78]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [79]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [80]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7543, 0.7141, 0.5337, 0.5172],
        [0.9411, 0.3772, 0.5014, 0.8059],
        [0.6387, 0.0289, 0.2511, 0.1232]])

In [81]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7543, 0.7141, 0.5337, 0.5172],
        [0.9411, 0.3772, 0.5014, 0.8059],
        [0.6387, 0.0289, 0.2511, 0.1232]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [82]:
some_tensor.size()

torch.Size([3, 4])

In [83]:
some_tensor.shape

torch.Size([3, 4])

In [91]:
# Create a tensor
tensor=torch.tensor([1,2,3])
#tensor =tensor + 10
tensor

tensor([1, 2, 3])

In [92]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [93]:
#Element Wise multiplication
print (tensor, "*" , tensor)
print(f"Eqals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Eqals:tensor([1, 4, 9])


In [94]:
torch.matmul(tensor,tensor)

tensor(14)

In [95]:
tensor

tensor([1, 2, 3])

In [99]:
%%time
value =0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value

CPU times: user 1.02 ms, sys: 0 ns, total: 1.02 ms
Wall time: 908 µs


tensor(14)

In [100]:
%%time
torch.matmul( tensor, tensor)

CPU times: user 533 µs, sys: 0 ns, total: 533 µs
Wall time: 402 µs


tensor(14)