In [ ]:
import torch
torch.__version__

'2.6.0+cu124'

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# scalar
# creating pythorch tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
#Random Tensors

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9283, 0.2290, 0.6594, 0.7622],
        [0.4001, 0.7293, 0.7297, 0.1134],
        [0.8106, 0.0301, 0.3733, 0.2825]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.2971, 0.9259, 0.1117],
        [0.1527, 0.0295, 0.2047],
        [0.8829, 0.9261, 0.7117]])

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7046, 0.8303, 0.2815, 0.7007],
        [0.9947, 0.6774, 0.6355, 0.4794],
        [0.8998, 0.2064, 0.9449, 0.2568]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7046, 0.8303, 0.2815, 0.7007],
        [0.9947, 0.6774, 0.6355, 0.4794],
        [0.8998, 0.2064, 0.9449, 0.2568]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
some_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a tensor
tensor=torch.tensor([1,2,3])
tensor =tensor + 10
tensor

tensor([11, 12, 13])

In [ ]:
torch.mul(tensor,10)

tensor([110, 120, 130])

In [47]:
!git config --global user.email "kimiafazeli90@gmail.com"

In [48]:
!git clone https://github.com/kimiafazeli1/Deep-Learning.git

Cloning into 'Deep-Learning'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.


In [50]:
!mv deep_learning_1.ipynb Deep-Learning/


mv: cannot stat 'deep_learning_1.ipynb': No such file or directory


In [51]:
!ls


Deep-Learning  sample_data
