In [43]:
import torch
torch.__version__

'2.6.0+cu124'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# scalar
# creating pythorch tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
#Random Tensors

In [13]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4251, 0.4724, 0.5112, 0.6838],
        [0.4384, 0.3223, 0.7437, 0.7849],
        [0.7110, 0.8023, 0.9728, 0.4707]])

In [14]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
torch.rand(3,3)

tensor([[0.5216, 0.0339, 0.2890],
        [0.4216, 0.9422, 0.6381],
        [0.9364, 0.3359, 0.5402]])

In [16]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

In [20]:
random_tensor.dtype

torch.float32

In [21]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8287, 0.6281, 0.0298, 0.7122],
        [0.1961, 0.6238, 0.5443, 0.6004],
        [0.6393, 0.8480, 0.6784, 0.8330]])

In [29]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8287, 0.6281, 0.0298, 0.7122],
        [0.1961, 0.6238, 0.5443, 0.6004],
        [0.6393, 0.8480, 0.6784, 0.8330]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [30]:
some_tensor.size()

torch.Size([3, 4])

In [31]:
some_tensor.shape

torch.Size([3, 4])

In [32]:
# Create a tensor
tensor=torch.tensor([1,2,3])
#tensor =tensor + 10
tensor

tensor([1, 2, 3])

In [33]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [34]:
#Element Wise multiplication
print (tensor, "*" , tensor)
print(f"Eqals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Eqals:tensor([1, 4, 9])


In [35]:
torch.matmul(tensor,tensor)

tensor(14)

In [36]:
tensor

tensor([1, 2, 3])

In [37]:
%%time
value =0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value

CPU times: user 1.52 ms, sys: 0 ns, total: 1.52 ms
Wall time: 17.8 ms


tensor(14)

In [38]:
%%time
torch.matmul( tensor, tensor)

CPU times: user 120 µs, sys: 0 ns, total: 120 µs
Wall time: 125 µs


tensor(14)

In [44]:
tensor_A= torch.tensor([[1,2],[3,4],[5,6]])

In [45]:
tensor_B=torch.tensor(([7,10],[8,11],[9,12]))
torch.mm(tensor_A,tensor_B) #torch.mm is torch.matnul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
tensor_A.shape

torch.Size([3, 2])

In [47]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [48]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [53]:
x=torch.arange(0,100,10)
x
x.dtype

torch.int64

In [50]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [52]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [54]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

Torch.mean() requires a tensor of float32

In [56]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))